services:
  backend:
    build: backend
    environment:
      CONTACTS_DB: ${CONTACTS_DB}
      CONTACTS_DB_USER: ${CONTACTS_DB_USER}
      CONTACTS_DB_PASSWORD: ${CONTACTS_DB_PASSWORD}
      CONTACTS_DB_PORT: 5432
      CONTACTS_DB_HOST: db
      ENVIRONMENT: prod
      OLLAMA_URL: http://ollama:11434
      LLM_MODEL: phonebook-llm

    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
  frontend:
    build:
      context: frontend
      args:
        VITE_API_URL: # leave blank to use same origin as frontend
    ports:
      - "8888:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
  db:
    image: postgres:17.2-alpine3.21
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: ${CONTACTS_DB}
      POSTGRES_USER: ${CONTACTS_DB_USER}
      POSTGRES_PASSWORD: ${CONTACTS_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - contacts-db-data:/var/lib/postgresql/data
  ollama:
    build: llm
    volumes:
      - contacts-llm-data:/root/.ollama
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          test -f /tmp/ollama_ready
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 10s
volumes:
  contacts-db-data:
  contacts-llm-data:

